### ISSUE TITLE
No logo at the categories

### ISSUE THREAD

**Issue by krold1** [Themekraft/Custom-Community#268]
Hi,

I updated CC yesterday. I have two problems:
1. On the front side whole text is shown. I want just a few first sentenecs to be shown. where can i change it?
2. date of the post isn't shown, can you tell me why?
3. i can't open the website on the mobile.

Can you please help me to arrange my site again?

PS.
Ev. Please inform if it is possible to copy all my old settings.

Thank you

Karolina

**Comment by ginsterbusch** [comment]
Note: This is a BUGTRACKER, not a forum. Please post multiple questions, help requests and similar stuff either to the official WordPress forum at https://wordpress.org/support/theme/custom-community

OR at the official Helpdesk at https://themekraft.zendesk.com/hc

So no, closing this "issue".
